name: Live Stream to Facebook & YouTube

on:
  workflow_dispatch:

jobs:
  go-live:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Repo کو checkout کریں
        uses: actions/checkout@v4

      - name: ffmpeg اور gdown انسٹال کریں
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg python3-pip
          pip install --upgrade gdown

      - name: لائیو اسٹریم شروع کریں
        run: |
          chmod +x stream.sh
          ./stream.sh
